name: Run Tests

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        php-versions: ["8.0", "8.1", "8.2", "8.3"]
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl, json, zlib
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-scripts

      - name: PHPUnit tests
        run: vendor/bin/phpunit tests
